const INFURA_API_KEY = process.env.INFURA_API_KEY;

const METAMASK_WALLET_ACCOUNT_PRIVATE_KEY = process.env.METAMASK_WALLET_ACCOUNT_PRIVATE_KEY;

// ray test touch <
const SOLANA_NODE_JSON_RPC_ENDPOINT = process.env.SOLANA_NODE_JSON_RPC_ENDPOINT;

const SOLANA_WALLET_ACCOUNT_PRIVATE_KEY = process.env.SOLANA_WALLET_ACCOUNT_PRIVATE_KEY;
// ray test touch >

export {
  INFURA_API_KEY,
  METAMASK_WALLET_ACCOUNT_PRIVATE_KEY,
  SOLANA_NODE_JSON_RPC_ENDPOINT,
  SOLANA_WALLET_ACCOUNT_PRIVATE_KEY
};