const INFURA_API_KEY = process.env.INFURA_API_KEY;

const WALLET_ACCOUNT_PRIVATE_KEY = process.env.WALLET_ACCOUNT_PRIVATE_KEY;

// ray test touch <
const SOLANA_NODE_JSON_RPC_ENDPOINT = process.env.SOLANA_NODE_JSON_RPC_ENDPOINT;
// ray test touch >

export {
  INFURA_API_KEY,
  WALLET_ACCOUNT_PRIVATE_KEY,
  SOLANA_NODE_JSON_RPC_ENDPOINT
};